const manga = [
    { name: 'Berserk', img: 'https://cdn.myanimelist.net/images/manga/1/157897.jpg', genre: 'Action', synopsis: `Guts, a former mercenary now known as the "Black Swordsman," is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything important to Guts for the purpose of fulfilling his own desires. Now marked for death, Guts becomes condemned to a fate in which he is relentlessly pursued by demonic beings. Setting out on a dreadful quest riddled with misfortune, Guts, armed with a massive sword and monstrous strength, will let nothing stop him, not even death itself, until he is finally able to take the head of the one who stripped him—and his loved one—of their humanity.` },
    { name: 'One Piece', img: "https://cdn.myanimelist.net/images/manga/2/253146.jpg", genre: 'Action', synopsis: `Gol D. Roger, a man referred to as the "Pirate King," is set to be executed by the World Government. But just before his demise, he confirms the existence of a great treasure, One Piece, located somewhere within the vast ocean known as the Grand Line. Announcing that One Piece can be claimed by anyone worthy enough to reach it, the Pirate King is executed and the Great Age of Pirates begins. Twenty-two years later, a young man by the name of Monkey D. Luffy is ready to embark on his own adventure, searching for One Piece and striving to become the new Pirate King. Armed with just a straw hat, a small boat, and an elastic body, he sets out on a fantastic journey to gather his own crew and a worthy ship that will take them across the Grand Line to claim the greatest status on the high seas.` },
    { name: 'Vagabond', img: "https://cdn.myanimelist.net/images/manga/1/259070.jpg", genre: 'Action', synopsis: `In 16th-century Japan, Shinmen Takezou is a wild, rough young man, in both his appearance and his actions. His aggressive nature has won him the collective reproach and fear of his village, leading him and his best friend, Matahachi Honiden, to run away in search of something grander than provincial life. The pair enlist in the Toyotomi army, yearning for glory—but when the Toyotomi suffer a crushing defeat at the hands of the Tokugawa Clan at the Battle of Sekigahara, the friends barely make it out alive. After the two are separated, Shinmen returns home on a self-appointed mission to notify the Hon'iden family of Matahachi's survival. He instead finds himself a wanted criminal, framed for his friend's supposed murder based on his history of violence. Upon being captured, he is strung up on a tree and left to die. An itinerant monk, the distinguished Takuan Soho, takes pity on the "devil child," secretly freeing Shinmen and christening him with a new name to avoid pursuit by the authorities: Musashi Miyamoto.` },
    {
        name: 'Monster', img: 'https://cdn.myanimelist.net/images/manga/3/258224.jpg', genre: 'Slice of Life', synopsis: `
    Kenzou Tenma, a renowned Japanese neurosurgeon working in post-war Germany, faces a difficult choice: to operate on Johan Liebert, an orphan boy on the verge of death, or on the mayor of Düsseldorf. In the end, Tenma decides to gamble his reputation by saving Johan, effectively leaving the mayor for dead. As a consequence of his actions, hospital director Heinemann strips Tenma of his position, and Heinemann's daughter Eva breaks off their engagement. Disgraced and shunned by his colleagues, Tenma loses all hope of a successful career—that is, until the mysterious killing of Heinemann gives him another chance. Nine years later, Tenma is the head of the surgical department and close to becoming the director himself. Although all seems well for him at first, he soon becomes entangled in a chain of gruesome murders that have taken place throughout Germany. The culprit is a monster—the same one that Tenma saved on that fateful day nine years ago.` },
    { name: 'Slam Dunk', img: "https://cdn.myanimelist.net/images/manga/2/258749.jpg", genre: 'Sports', synopsis: `Hanamichi Sakuragi, a tall, boisterous teenager with flame-red hair and physical strength beyond his years, is eager to put an end to his rejection streak of 50 and finally score a girlfriend as he begins his first year of Shohoku High. However, his reputation for delinquency and destructiveness precedes him, and most of his fellow students subsequently avoid him like the plague. As his first day of school ends, he is left with two strong thoughts: "I hate basketball" and "I need a girlfriend." Haruko Akagi, ignorant of Hanamichi's history of misbehavior, notices his immense height and unwittingly approaches him, asking whether or not he likes basketball. Overcome by the fact that a girl is speaking to him, the red-haired giant blurts out a yes despite his true feelings. At the gym, Haruko asks if he can do a slam dunk. Though a complete novice, Hanamachi palms the ball and makes the leap...but overshoots, slamming his head into the backboard. Amazed by his near-inhuman physical abilities, Haruko quickly notifies the school's basketball captain of his feat. With this, Hanamichi is unexpectedly thrust into a world of competition for a girl he barely knows, but he soon discovers that there is perhaps more to basketball than he once thought.` },
    {
        name: 'Oyasumi Punpun', img: 'https://cdn.myanimelist.net/images/manga/3/164420.jpg', genre: 'Slice of Life', synopsis: `Punpun Onodera is a normal 11-year-old boy living in Japan. Hopelessly idealistic and romantic, Punpun begins to see his life take a subtle—though nonetheless startling—turn to the adult when he meets the new girl in his class, Aiko Tanaka. It is then that the quiet boy learns just how fickle maintaining a relationship can be, and the surmounting difficulties of transitioning from a naïve boyhood to a convoluted adulthood. When his father assaults his mother one night, Punpun realizes another thing: those whom he looked up to were not as impressive as he once thought.

    As his problems increase, Punpun's once shy demeanor turns into voluntary reclusiveness. Rather than curing him of his problems and conflicting emotions, this merely intensifies them, sending him down the dark path of maturity in this grim coming-of-age saga.` },
    { name: "Grand Blue", img: "https://cdn.myanimelist.net/images/manga/2/166124.jpg", genre: 'Comedy', synopsis: `Among the seaside town of Izu's ocean waves and rays of shining sun, Iori Kitahara is just beginning his freshman year at Izu University. As he moves into his uncle's scuba diving shop, Grand Blue, he eagerly anticipates his dream college life, filled with beautiful girls and good friends. But things don't exactly go according to plan. Upon entering the shop, he encounters a group of rowdy, naked upperclassmen, who immediately coerce him into participating in their alcoholic activities. Though unwilling at first, Iori quickly gives in and becomes the heart and soul of the party. Unfortunately, this earns him the scorn of his cousin, Chisa Kotegawa, who walks in at precisely the wrong time. Undeterred, Iori still vows to realize his ideal college life, but will things go according to plan this time, or will his situation take yet another dive?` },
    {
        name: "Vinland Saga", img: 'https://cdn.myanimelist.net/images/manga/2/188925.jpg', genre: 'Action', synopsis: `Thorfinn, son of one of the Vikings' greatest warriors, is among the finest fighters in the merry band of mercenaries run by the cunning Askeladd, an impressive feat for a person his age. However, Thorfinn is not part of the group for the plunder it entails—instead, for having caused his family great tragedy, the boy has vowed to kill Askeladd in a fair duel. Not yet skilled enough to defeat him, but unable to abandon his vengeance, Thorfinn spends his boyhood with the mercenary crew, honing his skills on the battlefield among the war-loving Danes, where killing is just another pleasure of life.

    One day, when Askeladd receives word that Danish prince Canute has been taken hostage, he hatches an ambitious plot—one that will decide the next King of England and drastically alter the lives of Thorfinn, Canute, and himself. Set in 11th-century Europe, Vinland Saga tells a bloody epic in an era where violence, madness, and injustice are inescapable, providing a paradise for the battle-crazed and utter hell for the rest who live in it.` },
    {
        name: '20th Century Boys', img: 'https://cdn.myanimelist.net/images/manga/5/260006.jpg', genre: 'Slice of Life', synopsis: `As the 20th century approaches its end, people all over the world are anxious that the world is changing. And probably not for the better.

    Kenji Endo is a normal convenience store manager who's just trying to get by. But when he learns that one of his old friends going by the name "Donkey" has suddenly committed suicide, and that a new cult led by a figure known as "Friend" is becoming more notorious, Kenji starts to feel that something isn't right. With a few key clues left behind by his deceased friend, Kenji realizes that this cult is much more than he ever thought it would be—not only is this mysterious organization directly targeting him and his childhood friends, but the whole world also faces a grave danger that only the friends have the key to stop.` },
    { name: 'Land of the Lustrous', img: 'https://cdn.myanimelist.net/images/manga/1/115443.jpg', genre: 'Action', synopsis: `Long ago, Earth was struck by six meteorites, creating six moons and leaving a lone island in their wake. Those who could not make it to the island sank to the bottom of the ocean, where, over time, they slowly turned to crystal. As countless millennia passed, 28 of these crystallized lifeforms, known as the Lustrous, rose from the depths and resided on the island. Led by the wise Kongou-sensei, they must defend themselves against the seemingly infinite number of Lunarians, inhabitants of the moons who seek to harvest their valuable bodies for crafting weapons and jewelry.` },
    {
        name: 'March Comes in Like a Lion', img: 'https://cdn.myanimelist.net/images/manga/2/52283.jpg', genre: 'Action', synopsis: `Rei Kiriyama is an extraordinary shogi player. Among the few elites to have gone professional as a middle school student, he is considered a genius. But what lies behind his prodigious facade is a teenage boy who suffers immense pressure from both his family, and from the high expectations from the shogi community. Rei moves out to live a more independent life away from his family, but his unorganized lifestyle and unsociable personality show no signs of improvement.

    However, in a twist of fate that will prove to be a turning point in his life, Rei then encounters the Kawamoto sisters—the motherly Akari, the passionate Hinata, and the energetic Momo—who take great care of him. 3-gatsu no Lion tells the story of Rei as he reshapes his melancholic life and picks up the courage to begin facing the problems he evaded during his past.` },
    { name: 'Great Teacher Onizuka', img: 'https://cdn.myanimelist.net/images/manga/2/172982.jpg', genre: 'Comedy', synopsis: `Great Teacher Onizuka follows the incredible, though often ridiculous, antics of the titular teacher as he attempts to outwit and win over the cunning Class 3-4 that is determined to have him removed from the school. However, other obstacles present themselves throughout—including the frustrated, balding vice principal, Hiroshi Uchiyamada; old enemies from his biker days; and his own idiotic teaching methods. But Eikichi fights it all whilst trying to help his students, romance fellow teacher Azusa Fuyutsuki, and earn his self-proclaimed title.` },
    {
        name: 'Haikyu!!', img: 'https://cdn.myanimelist.net/images/manga/2/258225.jpg', genre: 'Sports', synopsis: `The whistle blows. The ball is up. A dig. A set. A spike.

    Volleyball. A sport where two teams face off, separated by a formidable, wall-like net.
    
    The "Little Giant," standing at only 170 cm, overcomes the towering net and the wall of blockers. The awe-inspired Shouyou Hinata looks on at the ace's crow-like figure. Determined to reach great heights like the Little Giant, small-statured Hinata finally manages to form a team in his last year of junior high school, and enters his first volleyball tournament. However, his team is utterly defeated in their first game against the powerhouse school Kitagawa Daiichi, led by the genius, but oppressive setter dubbed the "King of the Court," Tobio Kageyama.
    
    Hinata enrolls into Karasuno High School seeking to take revenge against Kageyama in an official high school match and to follow in the Little Giant's footsteps—but his plans are ruined when he opens the gymnasium door to find Kageyama as one of his teammates.` },
    {
        name: 'Chainsaw Man', img: 'https://cdn.myanimelist.net/images/manga/3/216464.jpg', genre: 'Action', synopsis: `Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.

    Unfortunately, he has outlived his usefulness and is murdered by a devil in contract with the yakuza. However, in an unexpected turn of events, Pochita merges with Denji's dead body and grants him the powers of a chainsaw devil. Now able to transform parts of his body into chainsaws, a revived Denji uses his new abilities to quickly and brutally dispatch his enemies. Catching the eye of the official devil hunters who arrive at the scene, he is offered work at the Public Safety Bureau as one of them. Now with the means to face even the toughest of enemies, Denji will stop at nothing to achieve his simple teenage dreams.
    ` },
    {
        name: 'Yokohama Shopping Trip', img: 'https://cdn.myanimelist.net/images/manga/1/171813.jpg', genre: 'Slice of Life', synopsis: `In a post-apocalyptic world where an environmental disaster led to the eruption of Mt. Fuji and the inundation of Yokohama, the age of humans is in its twilight. Alpha Hatsuseno is an android and the namesake of a small cafe outside Yokohama. As her owner is away on a trip indefinitely, she has been left responsible for running the cafe. Although she rarely gets any customers, Alpha remains outgoing and cheerful.

    While Alpha awaits her owner's homecoming, she explores the vicinity with her scooter and camera. Throughout her journeys, she meets new people and other androids, making memories along the way.` },
    {
        name: 'Blue Period', img: "https://cdn.myanimelist.net/images/manga/2/204827.jpg", genre: 'Slice of Life', synopsis: `Second-year high school student Yatora Yaguchi is bored with his normal life. He studies well and plays around with his friends, but in truth, he does not enjoy either of those activities. Bound by norms, he secretly envies those who do things differently.

    That is until he discovers the joy of drawing. When he sees a painting made by a member of the Art Club, Yatora becomes fascinated with the colors used in it. Later, in an art exercise, he tries to convey his language without words but instead through painting. After that experience, Yatora finds himself so invested in art that he decides that it is what he wants to do for a living. But there stand multiple obstacles in his way: his parents who are hesitant over his unique choices, his more experienced peers, and the study of a subject much deeper than he initially expected.` },
    {
        name: 'Hunter x Hunter', img: 'https://cdn.myanimelist.net/images/manga/2/253119.jpg', genre: 'Action', synopsis: `"Secret treasure hoards, undiscovered wealth... mystical places, unexplored frontiers... 'The mysterious unknown.' There's magic in such words for those captivated by its spell. They are called 'Hunters'!"

    Gon Freecss wants to become a Hunter so he can find his father, a man who abandoned him to pursue a life of adventure. But it's not that simple: only one in one hundred thousand can pass the Hunter Exam, and that is just the first obstacle on his journey. During the Hunter Exam, Gon befriends many other potential Hunters, such as the mysterious Killua; the revenge-driven Kurapika; and Leorio, who aims to become a doctor. There's a world of adventure and peril awaiting, and those who embrace it with open arms can become the greatest Hunters of them all!` },
    {
        name: 'Akira', img: 'https://cdn.myanimelist.net/images/manga/2/157929.jpg', genre: 'Action', synopsis: `1988: It is World War III. Tokyo is decimated by a mysterious black explosion, unmatched in magnitude.

    2019: Fast forward 31 years. Neo-Tokyo, hastily built on the ruins of old Tokyo, is a sprawling cityscape of neon extravaganza. It is a fusion of towering skyscrapers and cutting-edge technology that is permeated through and through with an explosive, hyper-violent cocktail of biker gangs, poverty, and revolutionaries. In this derelict metropolis live Tetsuo Shima and Shoutarou Kaneda, two bikers who are the best of friends and the fiercest of rivals, despite being affiliated with the same gang. Desperate to prove himself as Kaneda's equal, Tetsuo unwittingly pulls a stunt that culminates in the awakening of a cryptic existence that threatens to change both the face of Neo-Tokyo and the lives of those who call the city their home—the awakening of a government secret simply known as Akira.` },
    {
        name: 'Hajime no Ippo: The Fighting!', img: 'https://cdn.myanimelist.net/images/manga/2/250313.jpg', genre: 'Sports', synopsis: `Makunouchi Ippo is a 16-year-old high school student who helps his mother run the family business. His hefty workload impedes on his social life, making him an easy target for bullies. One day, while being beaten up by a group of high school students, Ippo is saved by a boxer named Mamoru Takamura, and is brought to the Kamogawa Boxing Gym.

    This afterschool bullying session turns his life around for the better as Ippo discovers his latent talent for boxing and decides to practice the sport professionally. However, Mamoru doubts Ippo's determination and assigns him a task deemed impossible to complete, but the resolute Ippo trains tirelessly to fulfill his mission. Along the way, he finds out what it means to attain true strength while making new friends and fighting formidable foes.` },
    {
        name: 'Dorohedoro', img: 'https://cdn.myanimelist.net/images/manga/3/258246.jpg', genre: 'Action', synopsis: `Hole—a dark, decrepit, and disorderly district where the strong prey on the weak and death is an ordinary occurrence—is all but befitting of the name given to it. A realm separated from law and ethics, it is a testing ground to the magic users who dominate it. As a race occupying the highest rungs of their society, the magic users think of the denizens of Hole as no more than insects. Murdered, mutilated, and made experiments without a second thought, the powerless Hole dwellers litter the halls of Hole's hospital on a daily basis.

    Possessing free access to and from the cesspool, and with little challenge to their authority, the magic users appear indomitable to most—aside for a few. Caiman, more reptile than man, is one such individual. He hunts them on a heedless quest for answers with only a trusted pair of bayonets and his immunity to magic. Cursed by his appearance and tormented by nightmares, magic users are his only clue to restoring his life to normal. With his biggest obstacle being his stomach, his female companion Nikaidou, who runs the restaurant Hungry Bug, is his greatest ally.
    
    Set in a gritty world of hellish design, Dorohedoro manages a healthy blend of comedy and lightheartedness with death and carnage. Taking plenty of twists and turns while following the lives of Hole's residents, it weaves a unique world of unearthly origin and dreary appearance not for the squeamish or easily disturbed.` },
    {
        name: 'Spy x Family', img: 'https://cdn.myanimelist.net/images/manga/3/219741.jpg', genre: 'Slice of Life', synopsis: `For the agent known as "Twilight," no order is too tall if it is for the sake of peace. Operating as Westalis' master spy, Twilight works tirelessly to prevent extremists from sparking a war with neighboring country Ostania. For his latest mission, he must investigate Ostanian politician Donovan Desmond by infiltrating his son's school: the prestigious Eden Academy. Thus, the agent faces the most difficult task of his career: get married, have a child, and play family.

    Twilight, or "Loid Forger," quickly adopts the unassuming orphan Anya to play the role of a six-year-old daughter and prospective Eden Academy student. For a wife, he comes across Yor Briar, an absent-minded office worker who needs a pretend partner of her own to impress her friends. However, Loid is not the only one with a hidden nature. Yor moonlights as the lethal assassin "Thorn Princess." For her, marrying Loid creates the perfect cover. Meanwhile, Anya is not the ordinary girl she appears to be; she is an esper, the product of secret experiments that allow her to read minds. Although she uncovers their true identities, Anya is thrilled that her new parents are cool secret agents! She would never tell them, of course. That would ruin the fun.` },
    {
        name: "Jujutsu Kaisen", img: 'https://cdn.myanimelist.net/images/manga/3/210341.jpg', genre: 'Action', synopsis: `Hidden in plain sight, an age-old conflict rages on. Supernatural monsters known as "Curses" terrorize humanity from the shadows, and powerful humans known as "Jujutsu" sorcerers use mystical arts to exterminate them. When high school student Yuuji Itadori finds a dried-up finger of the legendary Curse Sukuna Ryoumen, he suddenly finds himself joining this bloody conflict.

    Attacked by a Curse attracted to the finger's power, Yuuji makes a reckless decision to protect himself, gaining the power to combat Curses in the process but also unwittingly unleashing the malicious Sukuna into the world once more. Though Yuuji can control and confine Sukuna to his own body, the Jujutsu world classifies Yuuji as a dangerous, high-level Curse who must be exterminated.` },
    {
        name: 'Attack on Titan', img: 'https://cdn.myanimelist.net/images/manga/2/37846.jpg', genre: 'Action', synopsis: `Hundreds of years ago, horrifying creatures which resembled humans appeared. These mindless, towering giants, called "Titans," proved to be an existential threat, as they preyed on whatever humans they could find in order to satisfy a seemingly unending appetite. Unable to effectively combat the Titans, mankind was forced to barricade themselves within large walls surrounding what may very well be humanity's last safe haven in the world.

    In the present day, life within the walls has finally found peace, since the residents have not dealt with Titans for many years. Eren Yeager, Mikasa Ackerman, and Armin Arlert are three young children who dream of experiencing all that the world has to offer, having grown up hearing stories of the wonders beyond the walls. But when the state of tranquility is suddenly shattered by the attack of a massive 60-meter Titan, they quickly learn just how cruel the world can be. On that day, Eren makes a promise to himself that he will do whatever it takes to eradicate every single Titan off the face of the Earth, with the hope that one day, humanity will once again be able to live outside the walls without fear.` },
    {
        name: 'Witch Hat Atelier', img: 'https://cdn.myanimelist.net/images/manga/3/190005.jpg', genre: 'Slice of Life', synopsis: `Coco, a humble dressmaker's daughter, has always been fascinated by magic and the witches who cast it, despite the strict precautions they take to hide their methods from the public. However, when Coco takes advantage of a golden chance to spy on the skilled witch Qifrey, she realizes that her favorite picture book was a disguised magic book all along! In her excitement, she immediately starts testing out the various spells.

    When a spell causes a disaster in her home, Qifrey rescues her just in time and decides to train her, realizing that she is the first lead he has found that could help him track down the Brimmed Caps—a dangerous group of heretics who experiment with forbidden body-altering magic and spread magical artifacts among the commoners. But before Coco and Qifrey can confront the Brimmed Caps, she is going to have to improve her magical skills and learn to get along with Qifrey's other apprentices.` },
    {
        name: `Blank Canvas: My So-Called Artist's Journey`, img: 'https://cdn.myanimelist.net/images/manga/1/154270.jpg', genre: 'Slice of Life', synopsis: `Akiko Hayashi has soaring but strangely specific dreams: to make a successful manga debut while still in school, have her favorite actor star in its adaptation, and end up marrying him. However, she is far from having the motivation or skills to realize these hopes. When a friend introduces her to an unorthodox, backstreet art class taught by the strong-armed Kenzou Hidaka, called simply as "sensei," Akiko decides to enroll, expecting an easy ride and an automatic improvement in her art skills. To her chagrin, what she gets is something else entirely—a tough, demanding, and uncompromising teacher with absolutely no interest in manga.

    But when Akiko takes up Sensei's challenge of an intense schedule, she comes to recognize how much he cares about his students and forms a close bond with him. With Sensei's guidance, Akiko learns what is necessary to become a successful mangaka as well as what it means to be an adult.` },
    {
        name: 'Dandadan', img: 'https://cdn.myanimelist.net/images/manga/2/248746.jpg', genre: 'Action', synopsis: `After being aggressively rejected, Momo Ayase finds herself sulking when she stumbles across a boy being bullied. Saved by her rash kindness, the occult-obsessed boy attempts to speak to her about supernatural interests he believes they share. Rejecting his claims, Ayase proclaimed that she is instead a believer in ghosts, starting an argument between the two over which is real.

    In a bet to determine who's correct, the two decide to separately visit locations associated with both the occult and the supernatural—Ayase visiting the former and the boy visiting the latter. When the two reach their respective places, it turns out that neither of them was wrong and that both the occult and ghosts do exist.
    
    This marks the beginning of Ayase and the boy's adventure, who shares a name with Ayase's favorite idol—Ken Takakura, as they attempt to fix the surreal supernatural and sci-fi elements around them to return to a normal life.` },
    { name: 'Hiraysumi', img: 'https://cdn.myanimelist.net/images/manga/2/249992.jpg', genre: 'Slice of Life', synopsis: `29-year-old freeter Ikuta Hiroto is a carefree young man without a love life, regular job and no real worries about the future. Thanks to his kind disposition, he inherits an old house from the neighbourhood granny, where his 18-year-old cousin, Natsumi moves in with him to study art in Tokyo. This is a story about Hiroto and the people around him who struggle with life.` },
    { name: 'Happiness', img: 'https://cdn.myanimelist.net/images/manga/2/161562.jpg', genre: 'Slice of Life', synopsis: `Nothing interesting in happening in Makoto Ozaki’s first year of high school. His life is a series of quiet humiliations: low-grade bullies, unreliable friends, and the constant frustration of his adolescent lust. But one night, a pale, thin girl knocks him to the ground in an alley and offers him a choice. Now everything is different. Daylight is searingly bright. Food tastes awful. And worse than anything is the terrible, consuming thirst. The tiny shames of his old life have been replaced by two towering horrors: the truth of what will slake his awful craving and high school itself.` },
    { name: 'Ping Pong', img: 'https://cdn.myanimelist.net/images/manga/2/151416.jpg', genre: 'Sports', synopsis: `Makoto “Smile” Tsukimoto and his friend Yutaka “Peco” Hoshino have been playing table tennis since they were kids, but as they enter high school, they find that the game has changed. Seeing potential in them that they themselves don’t fully realize, the coach recruits them for the school team. Bringing out their best will mean challenging the top players from rival schools in the summer tournament, including an ace Chinese exchange student who almost made the Olympic team. With the pressure on, can Smile and Peco take the heat and make it into the finals?` },
    { name: 'Blade of the Immortal', img: 'https://cdn.myanimelist.net/images/manga/1/157919.jpg', genre: 'Action', synopsis: `Hiroaki Samura's Blade of the Immortal will keep you on edge! Manji, a ronin warrior of feudal Japan, has been cursed with immortality. To rid himself of this curse and end his life of misery, he must slay one thousand evil men! His quest begins when a young girl seeks his help in taking revenge on her parents' killers . . . and his quest won't end until the blood of a thousand has spilled!` },
    { name: 'My Hero Academia', img: 'https://cdn.myanimelist.net/images/manga/1/209370.jpg', genre: 'Action', synopsis: `Middle school student Izuku Midoriya wants to be a hero more than anything, but he hasn’t got an ounce of power in him. With no chance of ever getting into the prestigious U.A. High School for budding heroes, his life is looking more and more like a dead end. Then an encounter with All Might, the greatest hero of them all, gives him a chance to change his destiny…` },
    { name: 'Blood on the Tracks', img: 'https://cdn.myanimelist.net/images/manga/1/200350.jpg', genre: 'Slice of Life', synopsis: `Ordinary middle school student Seiichi Osabe receives love and care from his mother Seiko. Until one summer an incident changes the family dynamic forever. This is a story of a mother’s love that has gone too far….` },
    {
        name: 'Chihayafuru', img: 'https://cdn.myanimelist.net/images/manga/1/245072.jpg', genre: 'Sports', synopsis: `Chihaya is a girl in the sixth grade, still not old enough to even know the meaning of the word zeal. But one day, she meets Arata, a transfer student from rural Fukui prefecture. Though docile and quiet, he has an unexpected skill: his ability to play competitive karuta, a traditional Japanese card game.

    Chihaya is struck by his obsession with the game, along with his ability to pick out the right card and swipe it away before any of his opponents. However, Arata is transfixed by her as well, all because of her unbelievable natural talent for the game. Don't miss this story of adolescent lives and emotions playing out in the most dramatic of ways!` },
    {
        name: `Dead Dead Demon's Dededededestruction`, img: 'https://cdn.myanimelist.net/images/manga/3/142079.jpg', action: 'Slice of Life', synopsis: `The Japan Self-Defense Forces are still looking for a way to combat the alien threat, but so far conventional weapons have had no effect. Maybe it’s time to try something unconventional.

    Meanwhile, Kadode Koyama and her best friend avidly track the aliens’ movements on social media and less enthusiastically study for college entrance exams. When the end of the world looms overhead, you learn to take things one step at a time.` },
    { name: 'Silver Spoon', genre: 'Action', img: 'https://cdn.myanimelist.net/images/manga/1/231500.jpg', genre: 'Slice of Life', synopsis: `Defying the expectations of family and teachers, Yuugo Hachiken chooses to leave the city and enroll at Ooezo Agricultural High School. Having always been at the top of his class, Yuugo assumes a rural school will be a breeze, but mucking out stables, gathering eggs, and chasing errant calves takes a lot out of him-and fills him with something he's never experienced before. Surrounded by endless fields and fresh air, Yuugo discovers a new connection to the land and to life... Springtime begins at Ezo AG!!` },
    { name: 'Homunculus', img: 'https://cdn.myanimelist.net/images/manga/1/318.jpg', genre: 'Action', synopsis: `Trepanation is the procedure of drilling a hole in the skull. It is said to increase the blood circulation and improve pressure inside the skull. It is also said to bring out a person's sixth sense, the ability to use ESP, see ghosts, move objects with one's mind. This is speculative fiction based on the concept of trepanation.` },
    { name: 'Horimiya', img: 'https://cdn.myanimelist.net/images/manga/2/245008.jpg', genre: 'Romance', synopsis: `At school, Kyouko Hori is known for being smart, attractive, and popular. On the other hand, her classmate, the boring, gloomy Izumi Miyamura tends to get painted as a "loser fanboy." But when a liberally pierced and tattooed (not to mention downright gorgeous) Miyamura appears unexpectedly on the doorstep of secretly plain-Jane homebody Hori, these two similarly dissimilar teenagers discover that there are multiple sides to every story...and person!` },
    { name: 'Jagaaaaaaaan', img: 'https://cdn.myanimelist.net/images/manga/3/197327.jpg', genre: 'Action', synopsis: `Shintarou Jagasaki, who is a neighborhood police officer, lives with his girlfriend while working a job that is killing him slowly with annoyance. It looks like he will end up marrying soon and live a boring life with a nuclear family - a grim future for a guy with dreams! One such day, a mysterious monster appeared on the train and he suddenly can shoot with his right hand like Master Buppanatsu, the eggplant mascot of his city!` },
    { name: `Hell's paradise`, img: 'https://cdn.myanimelist.net/images/manga/2/208522.jpg', genre: 'Action', synopsis: `Gabimaru the Hollow is one of the most vicious assassins ever to come out of the ninja village of Iwagakure. He’s ruthlessly efficient, but a betrayal results in him being handed a death sentence. He has only one hope—in order to earn his freedom, he must travel to a long-hidden island and recover an elixir that will make the shogun immortal. Failure is not an option. On this island, heaven and hell are just a hair’s breadth away.` },
    { name: 'Lone Wolf & Cub', img: 'https://cdn.myanimelist.net/images/manga/1/159264.jpg', genre: 'Action', synopsis: `An epic samurai adventure of staggering proportions—over 7000 pages—Lone Wolf and Cub (Kozure Okami in Japan) is acknowledged worldwide for the brilliant writing of series creator Kazuo Koike and the groundbreaking cinematic visuals of the late Goseki Kojima, creating unforgettable imagery of stark beauty, kinetic fury, and visceral thematic power that influenced a generation of visual storytellers both in Japan and in the West.` },
    { name: 'Pluto', img: 'https://cdn.myanimelist.net/images/manga/1/264496.jpg', genre: 'Slice of Life', synopsis: `In an ideal world where man and robots coexist, someone or something has destroyed the powerful Swiss robot Mont Blanc. Elsewhere a key figure in a robot rights group is murdered. The two incidents appear to be unrelated...except for one very conspicuous clue - the bodies of both victims have been fashioned into some sort of bizarre collage complete with makeshift horns placed by the victims' heads. Interpol assigns robot detective Gesicht to this most strange and complex case - and he eventually discovers that he too, as one of the seven great robots of the world, is one of the targets.` },
    {
        name: 'Sanctuary', img: 'https://cdn.myanimelist.net/images/manga/1/170458.jpg', genre: 'Action', synopsis: `Two young men vow to transform the destiny of Japan, by any means. As children, they survived the horrors of the Cambodian killing fields together. Now, can they topple the leaders of both the Japanese Parliament and the yakuza crime syndicate?

    Although cold and calculating when need be, Hojo and Asami exemplify the traits their colleagues lack: loyalty to friends, compassion for the downtrodden...and an irresistible way with women.
    
    Deputy Police Chief Ishihara sets out to expose their ingenious machinations, but instead falls helplessly in love with Hojo...` },
    { name: 'Sunny', img: 'https://cdn.myanimelist.net/images/manga/1/151417.jpg', genre: 'Slice of Life', synopsis: `The story of an orphanage, the children who live in it, and the beat-up old Nissan Sunny 1200 which provides them with a means of escape from their boring everyday lives.` }
]
module.exports = manga