const manga = [
    { name: 'Bererk', img: 'https://cdn.myanimelist.net/images/manga/1/157897.jpg' },
    { name: 'One Piece', img: "https://cdn.myanimelist.net/images/manga/2/253146.jpg" },
    { name: 'Vagabond', img: "https://cdn.myanimelist.net/images/manga/1/259070.jpg" },
    { name: 'Monster', img: 'https://cdn.myanimelist.net/images/manga/3/258224.jpg' },
    { name: 'Slam Dunk', img: "https://cdn.myanimelist.net/images/manga/2/258749.jpg" },
    { name: 'Oyasumi Punpun', img: 'https://cdn.myanimelist.net/images/manga/3/164420.jpg' },
    { name: "Grand Blue", img: "https://cdn.myanimelist.net/images/manga/2/166124.jpg" },
    { name: "Vinland Saga", img: 'https://cdn.myanimelist.net/images/manga/2/188925.jpg' },
    { name: '20th Century Boys', img: 'https://cdn.myanimelist.net/images/manga/5/260006.jpg' },
    { name: 'Land of the Lustrous', img: 'https://cdn.myanimelist.net/images/manga/1/115443.jpg' },
    { name: 'March Comes in Like a Lion', img: 'https://cdn.myanimelist.net/images/manga/2/52283.jpg' },
    { name: 'Great Teacher Onizuka', img: 'https://cdn.myanimelist.net/images/manga/2/172982.jpg' },
    { name: 'Haikyu!!', img: 'https://cdn.myanimelist.net/images/manga/2/258225.jpg' },
    { name: 'Chainsaw Man', img: 'https://cdn.myanimelist.net/images/manga/3/216464.jpg' },
    { name: 'Yokohama Shopping Trip', img: 'https://cdn.myanimelist.net/images/manga/1/171813.jpg' },
    { name: 'Blue Period', img: "https://cdn.myanimelist.net/images/manga/2/204827.jpg" },
    { name: 'Hunter x Hunter', img: 'https://cdn.myanimelist.net/images/manga/2/253119.jpg' },
    { name: 'Akira', img: 'https://cdn.myanimelist.net/images/manga/2/157929.jpg' },
    { name: 'Hajime no Ippo: The Fighting!', img: 'https://cdn.myanimelist.net/images/manga/2/250313.jpg' },
    { name: 'Dorohedoro', img: 'https://cdn.myanimelist.net/images/manga/3/258246.jpg' },
    { name: 'Spy x Family', img: 'https://cdn.myanimelist.net/images/manga/3/219741.jpg' },
    { name: "Jujutsu Kaisen", img: 'https://cdn.myanimelist.net/images/manga/3/210341.jpg' },
    { name: 'Attack on Titan', img: 'https://cdn.myanimelist.net/images/manga/2/37846.jpg' },
    { name: 'Witch Hat Atelier', img: 'https://cdn.myanimelist.net/images/manga/3/190005.jpg' },
    { name: `Blank Canvas: My So-Called Artist's Journey`, img: 'https://cdn.myanimelist.net/images/manga/1/154270.jpg' },
    { name: 'Dandadan', img: 'https://cdn.myanimelist.net/images/manga/2/248746.jpg' },
    { name: 'Hiraysumi', img: 'https://cdn.myanimelist.net/images/manga/2/249992.jpg' },
    { name: 'Happiness', img: 'https://cdn.myanimelist.net/images/manga/2/161562.jpg' },
    { name: 'Ping Pong', img: 'https://cdn.myanimelist.net/images/manga/2/151416.jpg' },
    { name: 'Blade of the Immortal', img: 'https://cdn.myanimelist.net/images/manga/1/157919.jpg' },
    { name: 'My Hero Academia', img: 'https://cdn.myanimelist.net/images/manga/1/209370.jpg' },
    { name: 'Blood on the Tracks', img: 'https://cdn.myanimelist.net/images/manga/1/200350.jpg' },
    { name: 'Chihayafuru', img: 'https://cdn.myanimelist.net/images/manga/1/245072.jpg' },
    { name: `Dead Dead Demon's Dededededestruction`, img: 'https://cdn.myanimelist.net/images/manga/3/142079.jpg' },
    { name: 'Silver Spoon', img: 'https://cdn.myanimelist.net/images/manga/1/231500.jpg' },
    { name: 'Homunculus', img: 'https://cdn.myanimelist.net/images/manga/1/318.jpg' },
    { name: 'Horimiya', img: 'https://cdn.myanimelist.net/images/manga/2/245008.jpg' },
    { name: 'Jagaaaaaaaan', img: 'https://cdn.myanimelist.net/images/manga/3/197327.jpg' },
    { name: `Hell's paradise: Jigokuraku`, img: 'https://cdn.myanimelist.net/images/manga/2/208522.jpg' },
    { name: 'Lone Wolf & Cub', img: 'https://cdn.myanimelist.net/images/manga/1/159264.jpg' },
    { name: 'Pluto', img: 'https://cdn.myanimelist.net/images/manga/1/264496.jpg' },
    { name: 'Sanctuary', img: 'https://cdn.myanimelist.net/images/manga/1/170458.jpg' },
    { name: 'Sunny', img: 'https://cdn.myanimelist.net/images/manga/1/151417.jpg' }
]